### ISSUE TITLE
line 53

### ISSUE THREAD

**Issue by anisha6822** [madaari/zuckerrohr-stub#2]
https://github.com/Bonfarmo/zuckerrohr-stub/blob/be877db99f80eb3ad861543e6e0e287292a528da/scripts/main.py#L53

**Comment by uditagarwal97** [comment]
if (line[0] < mini) or (mini == 0):
   mini = line[0]
if line[0] > maxi:
   maxi = line[0]

These lines only selects the minimum and maximum x coordinate of the lines. Since, stub is in between these min and max values we just need them. In the next line see offset is combined with max and min values to get an enclosure for the stub + eye
